//
//  main.c
//  320Project2
//
//  Created by Mariya Mohiuddin on 14/05/2024.
//
#include <stdio.h>
#include <ctype.h>
#include <string.h>

int charClass;
char lexeme[100];
char nextChar;
int lexLen;
int token;
int nextToken;
FILE *in_fp;

/* Character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26
#define GREATER_THAN 27
#define LESS_THAN 28
#define EQUALS 29
#define IF_KEYWORD 30
#define ELSE_KEYWORD 31

void addChar();
void getChar();
void getNonBlank();
int lex();
int lookup(char ch);
void error(char *message);
void expr();
void term();
void factor();

int main() {
    /* Open the input data file and process its contents */
    if ((in_fp = fopen("/Users/mariyamohiuddin/Desktop/320Project2/320Project2/../../front.txt", "r")) == NULL) {
        printf("ERROR - cannot open input.txt\n");
        return 1; // Exit with error status
    } else {
        getChar();
        do {
            lex();
            expr();
        } while (nextToken != EOF);
        fclose(in_fp);
    }
    return 0; // Exit with success status
}

void addChar() {
    if (lexLen <= 98) {
        lexeme[lexLen++] = nextChar;
        lexeme[lexLen] = '\0'; // Null-terminate the string
    } else {
        printf("Error - lexeme is too long\n");
    }
}

void getChar() {
    if ((nextChar = getc(in_fp)) != EOF) {
        if (isalpha(nextChar))
            charClass = LETTER;
        else if (isdigit(nextChar))
            charClass = DIGIT;
        else
            charClass = UNKNOWN;
    } else {
        charClass = EOF;
    }
}

void getNonBlank() {
    while (isspace(nextChar))
        getChar();
}

int lex() {
    lexLen = 0;
    getNonBlank();
    switch (charClass) {
        case LETTER:
            addChar();
            getChar();
            // Transition to Identifier state
            while (charClass == LETTER || charClass == DIGIT) {
                addChar();
                getChar();
            }
            nextToken = IDENT;
            // Check if the identifier is a keyword
            if (strcmp(lexeme, "if") == 0)
                nextToken = IF_KEYWORD;
            else if (strcmp(lexeme, "else") == 0)
                nextToken = ELSE_KEYWORD;
            break;
        case DIGIT:
            addChar();
            getChar();
            // Transition to Integer Literal state
            while (charClass == DIGIT) {
                addChar();
                getChar();
            }
            nextToken = INT_LIT;
            break;
        case UNKNOWN:
            nextToken = lookup(nextChar);
            getChar();
            break;
        default:
            // Handle other cases
            nextToken = EOF;
            break;
    }
    printf("Next token is: %d, Next lexeme is '%s'\n", nextToken, lexeme);
    return nextToken;
}

int lookup(char ch) {
    switch (ch) {
        case '=':
            addChar();
            return ASSIGN_OP;
        case '+':
            addChar();
            return ADD_OP;
        case '-':
            addChar();
            getChar(); // Look ahead to determine if it's a negative number
            if (isdigit(nextChar)) {
                // Transition to Integer Literal state
                while (charClass == DIGIT) {
                    addChar();
                    getChar();
                }
                return INT_LIT;
            } else {
                // Not a negative number, return SUB_OP
                return SUB_OP;
            }
        case '*':
            addChar();
            return MULT_OP;
        case '/':
            addChar();
            return DIV_OP;
        case '(':
            addChar();
            return LEFT_PAREN;
        case ')':
            addChar();
            return RIGHT_PAREN;
        case '>':
            addChar();
            return GREATER_THAN;
        case '<':
            addChar();
            return LESS_THAN;
        default:
            if (isalpha(ch)) {
                addChar();
                return IDENT;
            } else if (isdigit(ch)) {
                addChar();
                return INT_LIT;
            } else {
                printf("Error: Illegal character '%c'\n", ch);
                getChar(); // Move to the next character
                return UNKNOWN;
            }
    }
}

void error(char *message) {
    printf("Error: %s\n", message);
}

/* expr
 Parses strings in the language generated by the rule:
 <expr> -> <term> {(+ | -) <term>}
 */
void expr() {
    printf("Enter <expr>\n");
    term();
    while (nextToken == ADD_OP || nextToken == SUB_OP ||
           nextToken == MULT_OP || nextToken == DIV_OP) {
        lex();
        // Check if the next token is a variable (IDENT)
        if (nextToken != IDENT) {
            error("Missing operator");
        }
        term();
    }
    printf("Exit <expr>\n");
}


/* term
 Parses strings in the language generated by the rule:
 <term> -> <factor> {(* | /) <factor>)
 */
void term() {
    printf("Enter <term>\n");
    factor();
    while (nextToken == MULT_OP || nextToken == DIV_OP) {
        lex();
        factor();
    }
    printf("Exit <term>\n");
}

/* factor
 Parses strings in the language generated by the rule:
 <factor> -> id | int_constant | ( <expr )
 */
void factor() {
    printf("Enter <factor>\n");
    if (nextToken == IDENT || nextToken == INT_LIT) {
        lex();
    } else {
        if (nextToken == LEFT_PAREN) {
            lex();
            expr();
            if (nextToken == RIGHT_PAREN)
                lex();
            else
                error("Missing right parenthesis");
        } else {
            error("Missing left parenthesis");
        }
    }
    printf("Exit <factor>\n");
}
